<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE jmxetric-config [
   <!ELEMENT jmxetric-config (sample|ganglia|jvm)*>
   <!ELEMENT sample (mbean)*>
      <!ATTLIST sample delay CDATA #REQUIRED>
      <!ATTLIST sample initialdelay CDATA "0">
      <!ATTLIST sample dmax CDATA "0" >
   <!ELEMENT mbean (attribute)*>
      <!ATTLIST mbean name CDATA #REQUIRED>
      <!ATTLIST mbean pname CDATA #REQUIRED>
   <!ELEMENT attribute (composite*)>
      <!ATTLIST attribute name CDATA #REQUIRED>
      <!ATTLIST attribute type CDATA "" >
      <!ATTLIST attribute units CDATA "" >
      <!ATTLIST attribute pname CDATA "" >
      <!ATTLIST attribute slope CDATA "both" >
      <!ATTLIST attribute dmax CDATA "0" >
   <!ELEMENT composite EMPTY>
      <!ATTLIST composite name CDATA #REQUIRED>
      <!ATTLIST composite type CDATA "" >
      <!ATTLIST composite units CDATA "" >
      <!ATTLIST composite pname CDATA "" >
      <!ATTLIST composite slope CDATA "both" >
      <!ATTLIST composite dmax CDATA "0" >
   <!ELEMENT ganglia EMPTY>
      <!ATTLIST ganglia hostname CDATA #REQUIRED>
      <!ATTLIST ganglia port CDATA #REQUIRED>
      <!ATTLIST ganglia mode CDATA #REQUIRED>
      <!ATTLIST ganglia wireformat31x CDATA #REQUIRED>
   <!ELEMENT jvm (process-name-solvers)*>
	<!ELEMENT process-name-solvers (process-name-solver)+>
	<!ELEMENT process-name-solver EMPTY>
		<!ATTLIST process-name-solver type (string|environment-variable|property-variable) "string" >
		<!ATTLIST process-name-solver value CDATA #REQUIRED >
]>
<jmxetric-config>
	<jvm>
		<process-name-solvers>
			<process-name-solver type="environment-variable" value="APPNAME" />
			<process-name-solver type="property-variable" value="app_name" />
			<process-name-solver type="environment-variable" value="PROCESSNAME" />
			<process-name-solver type="environment-variable" value="PROCESS_NAME" />
			<process-name-solver type="environment-variable" value="processName" />
			<process-name-solver type="property-variable" value="process_name" />
			<process-name-solver type="string" value="MyProcess" />
		</process-name-solvers>
	</jvm>
	<sample initialdelay="20" delay="60">
		<mbean name="java.lang:type=Memory" pname="Memory">
			<attribute name="HeapMemoryUsage">
				<composite name="init" pname="Heap_init" type="int32" units="bytes"/>
				<composite name="committed" pname="Heap_committed" type="int32" units="bytes"/>
				<composite name="used" pname="Heap_used" type="int32" units="bytes" />
				<composite name="max" pname="Heap_max" type="int32" units="bytes" />
			</attribute>
			<attribute name="NonHeapMemoryUsage" >
				<composite name="init" pname="NonHeap_init" type="int32"  units="bytes" />
				<composite name="committed" pname="NonHeap_committed" type="int32" units="bytes" />
				<composite name="used" pname="NonHeap_used" type="int32" units="bytes" />
				<composite name="max" pname="NonHeap_max" type="int32" units="bytes" />
			</attribute>
		</mbean>
		<mbean name="java.lang:type=Threading" pname="Threading" >
			<attribute name="ThreadCount" type="int16" />
			<attribute name="DaemonThreadCount" type="int16" />
		</mbean>
		<mbean name="java.lang:type=OperatingSystem" pname="OS" >
			<attribute name="ProcessCpuTime" type="int32" slope="positive"/>
			<!-- File descriptors can only be monitored on UNIX/Linux JVMs, not Windows -->
			<!-- <attribute name="OpenFileDescriptorCount" type="int32" units="bytes"/>
			<attribute name="MaxFileDescriptorCount" type="int32" units="bytes"/> -->
		</mbean>

		<!-- This is a sample configuration for a Tomcat server (AJP port) -->
		<!-- <mbean name='Catalina:type=GlobalRequestProcessor,name="ajp-bio-8009"' pname="ajp">
			<attribute name="requestCount" type="int32" slope="positive" units="hits"/>
		</mbean> -->

		<!-- This is a sample configuration for a Tomcat server (HTTP port) -->
		<mbean name='Catalina:type=GlobalRequestProcessor,name="http-bio-8080"' pname="http">
			<attribute name="requestCount" type="int32" slope="positive" units="hits"/>
		</mbean>

		<!-- This is a sample configuration for a JBoss 7 server (HTTP port) -->
		<!-- <mbean name="jboss.as:subsystem=web,connector=http" pname="http">
			<attribute name="requestCount" type="int32" slope="positive"/>
		</mbean> -->

		<!-- This is a sample configuration for a HornetQ server (message queue depth for queue named testQueue) -->
		<!-- <mbean name='org.hornetq:module=Core,type=Queue,address="jms.queue.testQueue",name="jms.queue.testQueue"' pname="queue_testQueue">
			<attribute name="MessageCount" type="int32" slope="both"/>
			<attribute name="ConsumerCount" type="int32" slope="both"/>
		</mbean> -->

                <!-- This is a sample configuration for an Apache ActiveMQ server (message queue named customer.orders) -->
                <!-- <mbean name='org.apache.activemq:BrokerName=localhost,Type=Queue,Destination=customer.orders' pname="queue_customer_orders">
                        <attribute name="QueueSize" type="int32" slope="both"/>
                        <attribute name="ConsumerCount" type="int32" slope="both"/>
                </mbean> -->
	</sample>
	<!--<ganglia hostname="localhost" port="8649" mode="multicast" wireformat31x="true" />-->
	<ganglia hostname="localhost" port="8649" mode="unicast" wireformat31x="true" />
</jmxetric-config>

