<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE jmxetric-config [
   <!ELEMENT jmxetric-config (sample|ganglia|jvm)*>
   <!ELEMENT sample (mbean)*>
      <!ATTLIST sample delay CDATA #REQUIRED>
      <!ATTLIST sample initialdelay CDATA "0">
      <!ATTLIST sample dmax CDATA "0" >
   <!ELEMENT mbean (attribute)*>
      <!ATTLIST mbean name CDATA #REQUIRED>
      <!ATTLIST mbean pname CDATA #REQUIRED>
      <!ATTLIST mbean dmax CDATA "0" >
   <!ELEMENT attribute (composite*)>
      <!ATTLIST attribute name CDATA #REQUIRED>
      <!ATTLIST attribute type CDATA "" >
      <!ATTLIST attribute units CDATA "" >
      <!ATTLIST attribute pname CDATA "" >
      <!ATTLIST attribute slope CDATA "both" >
      <!ATTLIST attribute dmax CDATA "0" >
   <!ELEMENT composite EMPTY>
      <!ATTLIST composite name CDATA #REQUIRED>
      <!ATTLIST composite type CDATA "" >
      <!ATTLIST composite units CDATA "" >
      <!ATTLIST composite pname CDATA "" >
      <!ATTLIST composite slope CDATA "both" >
      <!ATTLIST composite dmax CDATA "0" >
   <!ELEMENT ganglia EMPTY>
      <!ATTLIST ganglia hostname CDATA #REQUIRED>
      <!ATTLIST ganglia port CDATA #REQUIRED>
      <!ATTLIST ganglia mode CDATA #REQUIRED>
      <!ATTLIST ganglia wireformat31x CDATA #REQUIRED>
   <!ELEMENT jvm EMPTY>
      <!ATTLIST jvm process CDATA "">
]>
<jmxetric-config>
	<jvm process="ProcessName"/>
	<sample delay="3">
		<mbean name="java.lang:type=Memory" pname="Memory">
			<attribute name="HeapMemoryUsage">
				<composite name="init" pname="Heap_init" type="int32" units="bytes"/>
				<composite name="committed" pname="Heap_committed" type="int32" units="bytes"/>
				<composite name="used" pname="Heap_used" type="int32" units="bytes" />
				<composite name="max" pname="Heap_max" type="int32" units="bytes" />
			</attribute>
			<attribute name="NonHeapMemoryUsage" >
				<composite name="init" pname="NonHeap_init" type="int32"  units="bytes" />
				<composite name="committed" pname="NonHeap_committed" type="int32" units="bytes" />
				<composite name="used" pname="NonHeap_used" type="int32" units="bytes" />
				<composite name="max" pname="NonHeap_max" type="int32" units="bytes" />
			</attribute>
		</mbean>
	</sample>
	<sample delay="3" dmax="1">
		<mbean name="jmxetric:type=TestExample" pname="TestExample" dmax="2">
			<attribute name="Int" type="int32" />
			<attribute name="Long" type="int32" />
			<attribute name="Double" type="double" />
			<attribute name="Float" type="float" />
			<attribute name="String" type="string" />
			<attribute name="Counter" type="int32" slope="positive" />
			<attribute name="Composite" dmax="3">
				<composite name="date" pname="Composite_date" type="String" units="bytes"/>
				<composite name="integer" pname="Composite_integer" type="int32" units="bytes" dmax="4"/>
				<composite name="name" pname="Composite_name" type="int32" units="bytes" />
			</attribute>
		</mbean>
		
		<mbean name="java.lang:type=Threading" pname="Threading" >
			<attribute name="ThreadCount" type="int16" />
			<attribute name="DaemonThreadCount" type="int16" />
		</mbean>

		<mbean name="java.lang:type=Threading"  >
			<attribute name="ThreadCount" type="int16" />
			<attribute name="DaemonThreadCount" type="int16" />
		</mbean>

        <mbean name="java.lang:type=OperatingSystem" pname="OS" >
            <attribute name="ProcessCpuTime" type="int32" slope="positive"/>
        </mbean>
                             
	</sample>
	<ganglia hostname="localhost" port="8649" mode="multicast" wireformat31x="true" />
</jmxetric-config>

